<?php
$url = $this->serverUrl() . $this->url('authorize/activate', array(
    'email' => urlencode($email),
    'token' => $token,
));
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <!-- If you delete this meta tag, Half Life 3 will never be released. -->
    <meta name="viewport" content="width=device-width" />

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Account Activation</title>

    <link rel="stylesheet" type="text/css" href="http://authorize.dev/css/email.css" />

</head>

<body bgcolor="#FFFFFF">

<!-- HEADER -->
<table class="head-wrap" bgcolor="#999999">
    <tr>
        <td></td>
        <td class="header container" >

            <div class="content">
                <table bgcolor="#999999">
                    <tr>
                        <td></td>
                    </tr>
                </table>
            </div>

        </td>
        <td></td>
    </tr>
</table><!-- /HEADER -->


<!-- BODY -->
<table class="body-wrap">
    <tr>
        <td></td>
        <td class="container" bgcolor="#FFFFFF">

            <div class="content">
                <table>
                    <tr>
                        <td>
                            <h3>Hi, <?=$first_name?></h3>
                            <p class="lead">Thank you for signing up to <?=$this->serverUrl(true)?>!.</p>
                            <p>To activate your account, please click the following link below:</p>
                            <p><a href="<?=$url?>" class="btn">Reset Password! &raquo;</a></p>
                            <p>If the link doesn't work, copy and paste the following url into your web browser:</p>
                            <p><a href="<?=$url?>"><?=$url?></a></p>
                            <!-- Callout Panel -->
                        </td>
                    </tr>
                </table>
            </div><!-- /content -->

        </td>
        <td></td>
    </tr>
</table><!-- /BODY -->

<!-- FOOTER -->
<table class="footer-wrap">
    <tr>
        <td></td>
        <td class="container">

            <!-- content -->
            <div class="content">
                <table>
                    <tr>
                        <td align="center">
                            <p>
                                <a href="#">Terms</a> |
                                <a href="#">Privacy</a>
                            </p>
                        </td>
                    </tr>
                </table>
            </div><!-- /content -->

        </td>
        <td></td>
    </tr>
</table><!-- /FOOTER -->

</body>
</html>