<?=$this->fm()?>

<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('authorize/authenticate'));
$form->setAttribute('method', 'post');
$form->setAttribute('role', 'form');
?>

<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Please sign in</h3>
                </div>
                <div class="panel-body">
                    <?=$this->form()->openTag($form)?>
                        <fieldset>
                            <div class="form-group">
                                <?=$this->formInput($form->get('identity')->setAttribute('class', 'form-control'))?>
                            </div>
                            <div class="form-group">
                                <?=$this->formInput($form->get('credential')->setAttribute('class', 'form-control'))?>
                            </div>
                            <a href="<?=$this->url('authorize/forgot-password')?>" class="pull-right">Forgot Password?</a>
                            <div class="checkbox">
                                <label>
                                    <?=$this->formCheckbox($form->get('remember_me'))?>Remember Me
                                </label>
                            </div>
                            <?=$this->formInput(
                                $form->get('btnSubmit')->setAttribute('class', 'btn btn-lg btn-success btn-block')
                            )?>
                        </fieldset>
                    <?=$this->form()->closeTag()?>
                </div>
            </div>
        </div>
    </div>
</div>
