<?=$this->fm()?>

<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('authorize/forgot-password'));
$form->setAttribute('method', 'post');
$form->setAttribute('role', 'form');
?>

<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?=$this->translate('Forgotten Password?')?></h3>
                </div>
                <div class="panel-body">
                    <p>Please enter your registered email address below to reset your password.</p>
                    <?=$this->form()->openTag($form)?>
                        <fieldset>
                            <div class="form-group">
                                <?=$this->formInput($form->get('identity')->setAttribute('class', 'form-control'))?>
                            </div>
                            <?=$this->formInput(
                                $form->get('btnSubmit')->setAttribute('class', 'btn btn-lg btn-success btn-block')
                            )?>
                        </fieldset>
                    <?=$this->form()->closeTag()?>
                </div>
            </div>
        </div>
    </div>
</div>
